# Week 5 Day 1 - Pandas

[Pandas](https://pandas.pydata.org) is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. It is free software released under the three-clause BSD license.

In [1]:
import pandas as pd
# import as pd -

In [2]:
# make a dictionary with lists as values
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

In [3]:
mydataset # this is a dictionary

{'cars': ['BMW', 'Volvo', 'Ford'], 'passings': [3, 7, 2]}

In [5]:
# make it a dataframe
# use pd.DataFrame(dataset_name)
mycars = pd.DataFrame(mydataset)
mycars

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [6]:
#get the information of your dataframe
mycars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cars      3 non-null      object
 1   passings  3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [8]:
#get the shape of your dataframe
mycars.shape
# helps u see how much data ur dealing w/

(3, 2)

In [9]:
#get the columns
mycars.columns # tells u the columns u have on the data frame

Index(['cars', 'passings'], dtype='object')

In [10]:
#get the rows
mycars.values

array([['BMW', 3],
       ['Volvo', 7],
       ['Ford', 2]], dtype=object)

In [12]:
mycars.index.values # get the numbers

array([0, 1, 2])

In [13]:
#get the axis numbers
mycars.axes # gives the index - this is 0-3, increasing by 1

[RangeIndex(start=0, stop=3, step=1),
 Index(['cars', 'passings'], dtype='object')]

In [15]:
#get the first row
mycars.loc[0] # locate row at position 0

cars        BMW
passings      3
Name: 0, dtype: object

In [17]:
type(mycars.loc[0])

pandas.core.series.Series

In [16]:
mycars

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [18]:
#use a list of indexs:
mycars.loc[[0,2]] # range needs another hard bracket

   cars  passings
0   BMW         3
2  Ford         2

In [19]:
#get a column
mycars['cars'] # gets mycars at coloumn 'cars'

0      BMW
1    Volvo
2     Ford
Name: cars, dtype: object

In [20]:
#get the rows
mycars.loc[ [0,1,2]] # pull out the columns u want

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [21]:
#what are the datatypes of the dataframe
mycars.dtypes # helps break it down

cars        object
passings     int64
dtype: object

In [22]:
mycars.info

<bound method DataFrame.info of     cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2>

In [23]:
#change the column 'passings' to float
mycars['passings'] # gives us the vals in the column
#impose float val
mycars['passings'].astype('float') # applies float to all vals in column passings
    # only permanently changes it if u assign to variable

0    3.0
1    7.0
2    2.0
Name: passings, dtype: float64

In [25]:
#look at it again
mycars.dtypes

cars        object
passings     int64
dtype: object

In [26]:
# reassign
mycars['passings']=mycars['passings'].astype('float')

In [27]:
mycars.dtypes

cars         object
passings    float64
dtype: object

In [28]:
#get rid of the last row
mycars.drop(2) # drops row at index 2
# think of columns as indexes

    cars  passings
0    BMW       3.0
1  Volvo       7.0

In [29]:
mycars

# *** most methods don't permanently change the data, they only change it w/in that scope

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0

In [31]:
newDf = mycars.drop(2) # must make new data frame to permanently change it

In [32]:
newDf

    cars  passings
0    BMW       3.0
1  Volvo       7.0

In [34]:
#get rid of the passings column

newDf2 = newDf.drop('passings', axis = 'columns')
newDf2

    cars
0    BMW
1  Volvo

<!--  -->

### NaN & empty data

In [ ]:
# Nan - empty data , it is a place holder

In [36]:
import numpy as np

uglyData = {
  'cars': ["BMW", 'Jeep', "Ford", 'Chrysler'],
  'passings': [3, np.nan, 2, 'NaN']
}

uglyDF = pd.DataFrame(uglyData)

In [37]:
uglyDF

       cars passings
0       BMW        3
1      Jeep      NaN
2      Ford        2
3  Chrysler      NaN

In [39]:
#drop the Nan

uglyDF_clean = uglyDF.dropna() # made to drop null values 
# gets rid of whole row where the nan was

In [40]:
uglyDF_clean

       cars passings
0       BMW        3
2      Ford        2
3  Chrysler      NaN

In [42]:
#replace it with 0
uglyDF_clean2  = uglyDF.fillna(0) # instead of 0, u can also fill it w/ string values 
uglyDF_clean2

       cars passings
0       BMW        3
1      Jeep        0
2      Ford        2
3  Chrysler      NaN

<!--  -->

### .csv Files

**pd.read_csv** 

A simple way to store big data sets is to use CSV files (comma separated files).
CSV files contains plain text and is a well know format that can be read by everyone including Pandas.

*pd.read_csv(filepath_or_buffer, sep=’ ,’ , header=’infer’,  index_col=None, usecols=None, engine=None, skiprows=None, nrows=None)*

In [43]:
df = pd.read_csv("data/tv_shows.csv") # imports the csv and makes it pandas dataframe

In [44]:
df

,Unnamed: 0,title,year,runtime,rating,votes,genre,text
0,0,Game of Thrones,(2011 TV Series),55 mins.,9.5,"748,557","[u'Adventure', u'Drama', u'Fantasy']",Several noble families fight for control of th...
1,1,Breaking Bad,(2008 TV Series),45 mins.,9.5,"662,459","[u'Crime', u'Drama', u'Thriller']",A chemistry teacher diagnosed with a terminal ...
2,2,The Walking Dead,(2010 TV Series),44 mins.,8.7,"500,301","[u'Drama', u'Horror']",Sheriff's Deputy Rick Grimes leads a group of ...
3,3,The Big Bang Theory,(2007 TV Series),22 mins.,8.5,"438,226",[u'Comedy'],A woman who moves into an apartment across the...
4,4,Dexter,(2006 TV Series),55 mins.,8.9,"419,031","[u'Crime', u'Drama', u'Mystery', u'Thriller']",A Miami police forensics expert moonlights as ...
...,...,...,...,...,...,...,...,...
1969,1969,Cristela,(2014 TV Series),30 mins.,6.3,"1,510",[u'Comedy'],"In her sixth year of law school, Cristela is f..."
1970,1970,Power Rangers in Space,(1998 TV Series),30 mins.,7.2,"1,504","[u'Action', u'Adventure', u'Family', u'Sci-Fi']",The most evil forces of the universe (Rita &am...
1971,1971,Reading Rainbow,(1983 TV Series),30 mins.,8.5,"1,501",[u'Family'],Levar Burton introduces young viewers to illus...
1972,1972,Martial Law,(1998 TV Series),45 mins.,7.1,"1,501","[u'Comedy', u'Crime', u'Action']",A Shanghai cop who is a master of martial arts...
1973,1973,Beast Machines: Transformers,(1999 TV Series),30 mins.,6.9,"1,500","[u'Action', u'Animation', u'Sci-Fi']",The Maximals awaken on their home planet of Cy...

In [45]:
#get a preview
df.head() # gives u first few lines of ur data
# good for

,Unnamed: 0,title,year,runtime,rating,votes,genre,text
0,0,Game of Thrones,(2011 TV Series),55 mins.,9.5,"748,557","[u'Adventure', u'Drama', u'Fantasy']",Several noble families fight for control of th...
1,1,Breaking Bad,(2008 TV Series),45 mins.,9.5,"662,459","[u'Crime', u'Drama', u'Thriller']",A chemistry teacher diagnosed with a terminal ...
2,2,The Walking Dead,(2010 TV Series),44 mins.,8.7,"500,301","[u'Drama', u'Horror']",Sheriff's Deputy Rick Grimes leads a group of ...
3,3,The Big Bang Theory,(2007 TV Series),22 mins.,8.5,"438,226",[u'Comedy'],A woman who moves into an apartment across the...
4,4,Dexter,(2006 TV Series),55 mins.,8.9,"419,031","[u'Crime', u'Drama', u'Mystery', u'Thriller']",A Miami police forensics expert moonlights as ...

In [46]:
#what columns of the csv file
df.columns

Index(['Unnamed: 0', 'title', 'year', 'runtime', 'rating', 'votes', 'genre',
       'text'],
      dtype='object')

In [47]:
# Return the number of not empty cells for each column/row
# helps compare differences 
df.count()

Unnamed: 0    1974
title         1974
year          1974
runtime       1814
rating        1974
votes         1974
genre         1970
text          1941
dtype: int64

In [48]:
df2 = df.dropna()
df2.count()

Unnamed: 0    1792
title         1792
year          1792
runtime       1792
rating        1792
votes         1792
genre         1792
text          1792
dtype: int64

In [49]:
#only import the columns ["title", "year", "rating", "votes"]
df3 = pd.read_csv('data/tv_shows.csv', usecols = ["title", "year", "rating", "votes"])
df3.head()
# usecols - allows u to only read in certain columns from a csv

                 title              year  rating    votes
0      Game of Thrones  (2011 TV Series)     9.5  748,557
1         Breaking Bad  (2008 TV Series)     9.5  662,459
2     The Walking Dead  (2010 TV Series)     8.7  500,301
3  The Big Bang Theory  (2007 TV Series)     8.5  438,226
4               Dexter  (2006 TV Series)     8.9  419,031

In [50]:
df3.count()

title     1974
year      1974
rating    1974
votes     1974
dtype: int64

In [51]:
#what is the maximum rating? 

# first get ratings 
df3['rating'].max()

9.6

In [52]:
#what is the minimum rating?
df3['rating'].min()

1.8

In [53]:
#find the avg of all of the ratings
average = df3['rating'].mean()
average

7.486524822695036

In [55]:
df3.head()

                 title              year  rating    votes
0      Game of Thrones  (2011 TV Series)     9.5  748,557
1         Breaking Bad  (2008 TV Series)     9.5  662,459
2     The Walking Dead  (2010 TV Series)     8.7  500,301
3  The Big Bang Theory  (2007 TV Series)     8.5  438,226
4               Dexter  (2006 TV Series)     8.9  419,031

In [54]:
#what data types of the dataframe? 
df3.dtypes # gives the data types of each of the columns in the dataframe

title      object
year       object
rating    float64
votes      object
dtype: object

In [59]:
#can you change the datatype of votes?
df3['votes'] = df3['votes'].astype('float64')
# the votes have commas in them, and floats can't read commas
# so first to convert obj to float, u have to clean it and then convert

ValueError: could not convert string to float: '748,557'

In [60]:
df3

                             title              year  rating    votes
0                  Game of Thrones  (2011 TV Series)     9.5  748,557
1                     Breaking Bad  (2008 TV Series)     9.5  662,459
2                 The Walking Dead  (2010 TV Series)     8.7  500,301
3              The Big Bang Theory  (2007 TV Series)     8.5  438,226
4                           Dexter  (2006 TV Series)     8.9  419,031
...                            ...               ...     ...      ...
1969                      Cristela  (2014 TV Series)     6.3    1,510
1970        Power Rangers in Space  (1998 TV Series)     7.2    1,504
1971               Reading Rainbow  (1983 TV Series)     8.5    1,501
1972                   Martial Law  (1998 TV Series)     7.1    1,501
1973  Beast Machines: Transformers  (1999 TV Series)     6.9    1,500

[1974 rows x 4 columns]

In [63]:
#set the index to be the names of the tv show
# make the index the title
df4 = df3.set_index('title') # sets the index to the name of the column 'title'
# ... aka gets rid of the far left column

In [64]:
df4

                                          year  rating    votes
title
Game of Thrones               (2011 TV Series)     9.5  748,557
Breaking Bad                  (2008 TV Series)     9.5  662,459
The Walking Dead              (2010 TV Series)     8.7  500,301
The Big Bang Theory           (2007 TV Series)     8.5  438,226
Dexter                        (2006 TV Series)     8.9  419,031
...                                        ...     ...      ...
Cristela                      (2014 TV Series)     6.3    1,510
Power Rangers in Space        (1998 TV Series)     7.2    1,504
Reading Rainbow               (1983 TV Series)     8.5    1,501
Martial Law                   (1998 TV Series)     7.1    1,501
Beast Machines: Transformers  (1999 TV Series)     6.9    1,500

[1974 rows x 3 columns]

In [65]:
#get the year of hte new dataframe
df4['year']

title
Game of Thrones                 (2011 TV Series)
Breaking Bad                    (2008 TV Series)
The Walking Dead                (2010 TV Series)
The Big Bang Theory             (2007 TV Series)
Dexter                          (2006 TV Series)
                                      ...
Cristela                        (2014 TV Series)
Power Rangers in Space          (1998 TV Series)
Reading Rainbow                 (1983 TV Series)
Martial Law                     (1998 TV Series)
Beast Machines: Transformers    (1999 TV Series)
Name: year, Length: 1974, dtype: object

<!--  -->

### .json files

**pd.read_json**

JSON = Python Dictionary

JSON objects have the same format as Python dictionaries. If your JSON code is not in a file, but in a Python Dictionary, you can load it into a DataFrame directly.

In [99]:
dataJson = {
    'item1':{
        "0":60,
        "1":60,
        "2":60
    },
    'item2':{
        '0':100,
        '1':100,
        '2':100
    }
}

In [ ]:
dfjson = pd.DataFrame(dataJson)
# dont have an empty data frame and then add stuff 
#

In [66]:
#read in nationalParks.json
df = pd.read_json("data/nationalParks.json")
df.head()

,area,coordinates,date_established_readable,date_established_unix,description,image,nps_link,states,title,id,visitors,world_heritage_site
0,"{'acres': '49,057.36', 'square_km': '198.5'}","{'latitude': 44.35, 'longitude': -68.21}","February 26, 1919",-1604599200,Covering most of Mount Desert Island and other...,"{'url': 'acadia.jpg', 'attribution': 'PixelBay...",https://www.nps.gov/acad/index.htm,"[{'id': 'state_maine', 'title': 'Maine'}]",Acadia,park_acadia,"3,303,393",False
1,"{'acres': '8,256.67', 'square_km': '33.4'}","{'latitude': -14.25, 'longitude': -170.68}","October 31, 1988",594280800,The southernmost National Park is on three Sam...,"{'url': 'american-samoa.jpg', 'attribution': '...",https://www.nps.gov/npsa/index.htm,"[{'id': 'state_american-samoa', 'title': 'Amer...",American Samoa,park_american-samoa,"28,892",False
2,"{'acres': '76,678.98', 'square_km': '310.3'}","{'latitude': 38.68, 'longitude': -109.57}","November 12, 1971",58773600,"This site features more than 2,000 natural san...","{'url': 'arches.jpg', 'attribution': 'PixelBay...",https://www.nps.gov/arch/index.htm,"[{'id': 'state_utah', 'title': 'Utah'}]",Arches,park_arches,"1,585,718",False
3,"{'acres': '242,755.94', 'square_km': '982.4'}","{'latitude': 43.75, 'longitude': -102.5}","November 10, 1978",279525600,"The Badlands are a collection of buttes, pinna...","{'url': 'badlands.jpg', 'attribution': 'PixelB...",https://www.nps.gov/badl/index.htm,"[{'id': 'state_south-dakota', 'title': 'South ...",Badlands,park_badlands,"996,263",False
4,"{'acres': '801,163.21', 'square_km': '3,242.2'}","{'latitude': 29.25, 'longitude': -103.25}","June 12, 1944",-806439600,Named for the prominent bend in the Rio Grande...,"{'url': 'big-bend.jpg', 'attribution': 'PixelB...",https://www.nps.gov/bibe/index.htm,"[{'id': 'state_texas', 'title': 'Texas'}]",Big Bend,park_big-bend,"388,290",False

In [67]:
df.dtypes

area                         object
coordinates                  object
date_established_readable    object
date_established_unix         int64
description                  object
image                        object
nps_link                     object
states                       object
title                        object
id                           object
visitors                     object
world_heritage_site            bool
dtype: object

In [79]:
#only get the ['date_established_readable','description', 'title', 'visitors', 'world_heritage_site', 'states ]

# how we get list of rows 


df2 = df[['title','visitors', 'date_established_readable','description', 'world_heritage_site', 'states' ]]
df2.head()
# u can change which rows come first/move around the order

,title,visitors,date_established_readable,description,world_heritage_site,states
0,Acadia,"3,303,393","February 26, 1919",Covering most of Mount Desert Island and other...,False,"[{'id': 'state_maine', 'title': 'Maine'}]"
1,American Samoa,"28,892","October 31, 1988",The southernmost National Park is on three Sam...,False,"[{'id': 'state_american-samoa', 'title': 'Amer..."
2,Arches,"1,585,718","November 12, 1971","This site features more than 2,000 natural san...",False,"[{'id': 'state_utah', 'title': 'Utah'}]"
3,Badlands,"996,263","November 10, 1978","The Badlands are a collection of buttes, pinna...",False,"[{'id': 'state_south-dakota', 'title': 'South ..."
4,Big Bend,"388,290","June 12, 1944",Named for the prominent bend in the Rio Grande...,False,"[{'id': 'state_texas', 'title': 'Texas'}]"

In [73]:
#get the datatypes
df2.dtypes

title                        object
date_established_readable    object
description                  object
visitors                     object
world_heritage_site            bool
states                       object
dtype: object

In [75]:
#find the national parks that are world heritage sites

# we don't need to iterate  - that sh;d be last case
# instead, subscript
whsNum = df2[df2['world_heritage_site'] == True]
whsNum # gives us subsection of the data frame with this qual

,title,date_established_readable,description,visitors,world_heritage_site,states
10,Carlsbad Caverns,"May 14, 1930","Carlsbad Caverns has 117 caves, the longest of...","466,773",True,"[{'id': 'state_new-mexico', 'title': 'New Mexi..."
18,Everglades,"May 30, 1934",The Everglades are the largest tropical wilder...,"930,907",True,"[{'id': 'state_florida', 'title': 'Florida'}]"
20,Glacier,"May 11, 1910",The U.S. half of Waterton-Glacier Internationa...,"2,946,681",True,"[{'id': 'state_montana', 'title': 'Montana'}]"
21,Glacier Bay,"December 2, 1980","Glacier Bay contains tidewater glaciers, mount...","520,171",True,"[{'id': 'state_alaska', 'title': 'Alaska'}]"
22,Grand Canyon,"February 26, 1919","The Grand Canyon, carved by the mighty Colorad...","5,969,811",True,"[{'id': 'state_arizona', 'title': 'Arizona'}]"
26,Great Smoky Mountains,"June 15, 1934","The Great Smoky Mountains, part of the Appalac...","11,312,786",True,"[{'id': 'state_tennessee', 'title': 'Tennessee..."
29,Hawaii Volcanoes,"August 1, 1916",This park on the Big Island protects the Kīlau...,"1,887,580",True,"[{'id': 'state_hawaii', 'title': 'Hawaii'}]"
39,Mammoth Cave,"July 1, 1941",With more than 400 miles (640 km) of passagewa...,"586,514",True,"[{'id': 'state_kentucky', 'title': 'Kentucky'}]"
40,Mesa Verde,"June 29, 1906","This area constitutes over 4,000 archaeologica...","583,527",True,"[{'id': 'state_colorado', 'title': 'Colorado'}]"
43,Olympic,"June 29, 1938","Situated on the Olympic Peninsula, this park i...","3,390,221",True,"[{'id': 'state_washington', 'title': 'Washingt..."
46,Redwood,"October 2, 1968",This park and the co-managed state parks prote...,"536,297",True,"[{'id': 'state_california', 'title': 'Californ..."
55,Wrangell–St. Elias,"December 2, 1980","An over 8 million acres (32,375 km2) plot of m...","79,047",True,"[{'id': 'state_alaska', 'title': 'Alaska'}]"
56,Yellowstone,"March 1, 1872","Situated on the Yellowstone Caldera, the park ...","4,257,177",True,"[{'id': 'state_wyoming', 'title': 'Wyoming'}, ..."
57,Yosemite,"October 1, 1890","Yosemite features sheer granite cliffs, except...","5,028,868",True,"[{'id': 'state_california', 'title': 'Californ..."

In [76]:
len(whsNum) # 14 national parks that are world heritage sites

14

<!--  -->

#### Exercise 1: get the national parks with over a million visitors

In [80]:
df2.head()

,title,visitors,date_established_readable,description,world_heritage_site,states
0,Acadia,"3,303,393","February 26, 1919",Covering most of Mount Desert Island and other...,False,"[{'id': 'state_maine', 'title': 'Maine'}]"
1,American Samoa,"28,892","October 31, 1988",The southernmost National Park is on three Sam...,False,"[{'id': 'state_american-samoa', 'title': 'Amer..."
2,Arches,"1,585,718","November 12, 1971","This site features more than 2,000 natural san...",False,"[{'id': 'state_utah', 'title': 'Utah'}]"
3,Badlands,"996,263","November 10, 1978","The Badlands are a collection of buttes, pinna...",False,"[{'id': 'state_south-dakota', 'title': 'South ..."
4,Big Bend,"388,290","June 12, 1944",Named for the prominent bend in the Rio Grande...,False,"[{'id': 'state_texas', 'title': 'Texas'}]"

In [90]:
df2_cleanVis = df2 

# get just the column w/ visitors
df2_cleanVis['visitors'] = df2_cleanVis['visitors'].replace(",","", regex = True)
df2_cleanVis.head()

/var/folders/89/1xx8slwx0sz7bb2jd1vmzghh0000gn/T/ipykernel_15602/1920574099.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_cleanVis['visitors'] = df2_cleanVis['visitors'].replace(",","", regex = True)

,title,visitors,date_established_readable,description,world_heritage_site,states
0,Acadia,3303393,"February 26, 1919",Covering most of Mount Desert Island and other...,False,"[{'id': 'state_maine', 'title': 'Maine'}]"
1,American Samoa,28892,"October 31, 1988",The southernmost National Park is on three Sam...,False,"[{'id': 'state_american-samoa', 'title': 'Amer..."
2,Arches,1585718,"November 12, 1971","This site features more than 2,000 natural san...",False,"[{'id': 'state_utah', 'title': 'Utah'}]"
3,Badlands,996263,"November 10, 1978","The Badlands are a collection of buttes, pinna...",False,"[{'id': 'state_south-dakota', 'title': 'South ..."
4,Big Bend,388290,"June 12, 1944",Named for the prominent bend in the Rio Grande...,False,"[{'id': 'state_texas', 'title': 'Texas'}]"

In [88]:
df2_cleanVis.dtypes

title                        object
visitors                     object
date_established_readable    object
description                  object
world_heritage_site            bool
states                       object
dtype: object

In [94]:
# change  the data type of visitors column to float 
df2_cleanVis['visitors'] = df2_cleanVis['visitors'].astype('int')
df2_cleanVis.head()

/var/folders/89/1xx8slwx0sz7bb2jd1vmzghh0000gn/T/ipykernel_15602/797180674.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_cleanVis['visitors'] = df2_cleanVis['visitors'].astype('int')

,title,visitors,date_established_readable,description,world_heritage_site,states
0,Acadia,3303393,"February 26, 1919",Covering most of Mount Desert Island and other...,False,"[{'id': 'state_maine', 'title': 'Maine'}]"
1,American Samoa,28892,"October 31, 1988",The southernmost National Park is on three Sam...,False,"[{'id': 'state_american-samoa', 'title': 'Amer..."
2,Arches,1585718,"November 12, 1971","This site features more than 2,000 natural san...",False,"[{'id': 'state_utah', 'title': 'Utah'}]"
3,Badlands,996263,"November 10, 1978","The Badlands are a collection of buttes, pinna...",False,"[{'id': 'state_south-dakota', 'title': 'South ..."
4,Big Bend,388290,"June 12, 1944",Named for the prominent bend in the Rio Grande...,False,"[{'id': 'state_texas', 'title': 'Texas'}]"

In [95]:
df2_cleanVis.dtypes

title                        object
visitors                      int64
date_established_readable    object
description                  object
world_heritage_site            bool
states                       object
dtype: object

In [96]:
milVis = df2_cleanVis[df2_cleanVis['visitors']>1000000] # check to make sure its over 1 mill visitors

In [97]:
milVis

,title,visitors,date_established_readable,description,world_heritage_site,states
0,Acadia,3303393,"February 26, 1919",Covering most of Mount Desert Island and other...,False,"[{'id': 'state_maine', 'title': 'Maine'}]"
2,Arches,1585718,"November 12, 1971","This site features more than 2,000 natural san...",False,"[{'id': 'state_utah', 'title': 'Utah'}]"
7,Bryce Canyon,2365110,"February 25, 1928",Bryce Canyon is a geological amphitheater on t...,False,"[{'id': 'state_utah', 'title': 'Utah'}]"
9,Capitol Reef,1064904,"December 18, 1971",The park's Waterpocket Fold is a 100-mile (160...,False,"[{'id': 'state_utah', 'title': 'Utah'}]"
14,Cuyahoga Valley,2423390,"October 11, 2000",This park along the Cuyahoga River has waterfa...,False,"[{'id': 'state_ohio', 'title': 'Ohio'}]"
15,Death Valley,1296283,"October 31, 1994","Death Valley is the hottest, lowest, and dries...",False,"[{'id': 'state_california', 'title': 'Californ..."
20,Glacier,2946681,"May 11, 1910",The U.S. half of Waterton-Glacier Internationa...,True,"[{'id': 'state_montana', 'title': 'Montana'}]"
22,Grand Canyon,5969811,"February 26, 1919","The Grand Canyon, carved by the mighty Colorad...",True,"[{'id': 'state_arizona', 'title': 'Arizona'}]"
23,Grand Teton,3270076,"February 26, 1929",Grand Teton is the tallest mountain in the Tet...,False,"[{'id': 'state_wyoming', 'title': 'Wyoming'}]"
26,Great Smoky Mountains,11312786,"June 15, 1934","The Great Smoky Mountains, part of the Appalac...",True,"[{'id': 'state_tennessee', 'title': 'Tennessee..."
28,Haleakala,1263558,"August 1, 1916",The Haleakala volcano on Maui features a very ...,False,"[{'id': 'state_hawaii', 'title': 'Hawaii'}]"
29,Hawaii Volcanoes,1887580,"August 1, 1916",This park on the Big Island protects the Kīlau...,True,"[{'id': 'state_hawaii', 'title': 'Hawaii'}]"
30,Hot Springs,1544300,"March 4, 1921",Hot Springs was established by act of Congress...,False,"[{'id': 'state_arkansas', 'title': 'Arkansas'}]"
32,Joshua Tree,2505286,"October 31, 1994",Covering large areas of the Colorado and Mojav...,False,"[{'id': 'state_california', 'title': 'Californ..."
41,Mount Rainier,1356913,"March 2, 1899","Mount Rainier, an active stratovolcano, is the...",False,"[{'id': 'state_washington', 'title': 'Washingt..."
43,Olympic,3390221,"June 29, 1938","Situated on the Olympic Peninsula, this park i...",True,"[{'id': 'state_washington', 'title': 'Washingt..."
47,Rocky Mountain,4517585,"January 26, 1915",Bisected north to south by the Continental Div...,False,"[{'id': 'state_colorado', 'title': 'Colorado'}]"
49,Sequoia,1254688,"September 25, 1890","This park protects the Giant Forest, which boa...",False,"[{'id': 'state_california', 'title': 'Californ..."
50,Shenandoah,1437341,"December 26, 1935",Shenandoah's Blue Ridge Mountains are covered ...,False,"[{'id': 'state_virginia', 'title': 'Virginia'}]"
56,Yellowstone,4257177,"March 1, 1872","Situated on the Yellowstone Caldera, the park ...",True,"[{'id': 'state_wyoming', 'title': 'Wyoming'}, ..."
57,Yosemite,5028868,"October 1, 1890","Yosemite features sheer granite cliffs, except...",True,"[{'id': 'state_california', 'title': 'Californ..."
58,Zion,4295127,"November 19, 1919",Located at the junction of the Colorado Platea...,False,"[{'id': 'state_utah', 'title': 'Utah'}]"

<!--  -->

### Exercise 2: Create a dictionary of the number of national parks per state

In [104]:
df2['states'][0] # grabs first row in states columnn

[{'id': 'state_maine', 'title': 'Maine'}]

In [105]:
type(df2['states'][0]) # is a list

list

In [108]:
# get first item in list 
df2['states'][0][0] # gets first item at first row of state column
# this is a dict

{'id': 'state_maine', 'title': 'Maine'}

In [109]:
df2['states'][0][0]['title']

'Maine'

In [110]:
df2_big = df2.explode('states')
df2_big.head()

,title,visitors,date_established_readable,description,world_heritage_site,states
0,Acadia,3303393,"February 26, 1919",Covering most of Mount Desert Island and other...,False,"{'id': 'state_maine', 'title': 'Maine'}"
1,American Samoa,28892,"October 31, 1988",The southernmost National Park is on three Sam...,False,"{'id': 'state_american-samoa', 'title': 'Ameri..."
2,Arches,1585718,"November 12, 1971","This site features more than 2,000 natural san...",False,"{'id': 'state_utah', 'title': 'Utah'}"
3,Badlands,996263,"November 10, 1978","The Badlands are a collection of buttes, pinna...",False,"{'id': 'state_south-dakota', 'title': 'South D..."
4,Big Bend,388290,"June 12, 1944",Named for the prominent bend in the Rio Grande...,False,"{'id': 'state_texas', 'title': 'Texas'}"

In [112]:
df2_big['states'][0]['title']

'Maine'

In [113]:
# make new column
df2_big['states_id'] = df2_big['states']#[:]['id']
df2_big.head()

,title,visitors,date_established_readable,description,world_heritage_site,states,states_id
0,Acadia,3303393,"February 26, 1919",Covering most of Mount Desert Island and other...,False,"{'id': 'state_maine', 'title': 'Maine'}","{'id': 'state_maine', 'title': 'Maine'}"
1,American Samoa,28892,"October 31, 1988",The southernmost National Park is on three Sam...,False,"{'id': 'state_american-samoa', 'title': 'Ameri...","{'id': 'state_american-samoa', 'title': 'Ameri..."
2,Arches,1585718,"November 12, 1971","This site features more than 2,000 natural san...",False,"{'id': 'state_utah', 'title': 'Utah'}","{'id': 'state_utah', 'title': 'Utah'}"
3,Badlands,996263,"November 10, 1978","The Badlands are a collection of buttes, pinna...",False,"{'id': 'state_south-dakota', 'title': 'South D...","{'id': 'state_south-dakota', 'title': 'South D..."
4,Big Bend,388290,"June 12, 1944",Named for the prominent bend in the Rio Grande...,False,"{'id': 'state_texas', 'title': 'Texas'}","{'id': 'state_texas', 'title': 'Texas'}"

In [114]:
stateParks = {}
# get data in each of states column

for i in df2_big['states']:
    
    # get j the names of the state
    stateName = i['title']

    # add the num of each instance to a dict
    if stateName in stateParks.keys():
        stateParks[stateName] += 1
    else:
        stateParks[stateName] = 1

In [115]:
stateParks

{'Maine': 1,
 'American Samoa': 1,
 'Utah': 5,
 'South Dakota': 2,
 'Texas': 2,
 'Florida': 3,
 'Colorado': 4,
 'New Mexico': 1,
 'California': 9,
 'South Carolina': 1,
 'Oregon': 1,
 'Ohio': 1,
 'Nevada': 2,
 'Alaska': 8,
 'Montana': 2,
 'Arizona': 3,
 'Wyoming': 2,
 'Tennessee': 1,
 'North Carolina': 1,
 'Hawaii': 2,
 'Arkansas': 1,
 'Michigan': 1,
 'Kentucky': 1,
 'Washington': 3,
 'Virginia': 1,
 'North Dakota': 1,
 'US Virgin Islands': 1,
 'Minnesota': 1,
 'Idaho': 1}